### ISSUE TITLE
Boost 1.69.0 produces errors

### ISSUE THREAD

**Issue by zerothi** [mhekkel/libzeep#8]
Trying to build zeep with boost 1.69.0.

I get the following error:

```bash
src/preforked-http-server.cpp: In static member function 'static bool zeep::http::preforked_server::read_socket_from_parent(int, boost::asio::ip::tcp::socket&)':
src/preforked-http-server.cpp:209:40: error: 'native_type' in 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} does not name a type
  typedef boost::asio::ip::tcp::socket::native_type native_type;
                                        ^~~~~~~~~~~
src/preforked-http-server.cpp:257:5: error: 'native_type' was not declared in this scope
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
     ^~~~~~~~~~~
src/preforked-http-server.cpp:257:5: note: suggested alternative:
In file included from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/cv_status.hpp:12,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/pthread/condition_variable_fwd.hpp:12,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/pthread/thread_data.hpp:14,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/thread_only.hpp:17,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/thread.hpp:12,
                 from ./zeep/http/server.hpp:10,
                 from ./zeep/http/preforked-server.hpp:9,
                 from src/preforked-http-server.cpp:15:
/opt/gnu/8.3.0/boost/1.69.0/include/boost/core/scoped_enum.hpp:73:10: note:   'boost::native_type'
   struct native_type
          ^~~~~~~~~~~
src/preforked-http-server.cpp:257:18: error: 'fdptr' was not declared in this scope
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                  ^~~~~
src/preforked-http-server.cpp:257:18: note: suggested alternative: 'cmptr'
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                  ^~~~~
                  cmptr
src/preforked-http-server.cpp:257:43: error: 'native_type' does not name a type; did you mean 'status_type'?
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                           ^~~~~~~~~~~
                                           status_type
src/preforked-http-server.cpp:257:54: error: expected '>' before '*' token
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                      ^
src/preforked-http-server.cpp:257:54: error: expected '(' before '*' token
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                      ^
                                                      (
src/preforked-http-server.cpp:257:55: error: expected primary-expression before '>' token
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                       ^
src/preforked-http-server.cpp:257:74: error: expected ')' before ';' token
     native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                                          ^
                                                                          ^
                                                                          )
src/preforked-http-server.cpp: In static member function 'static void zeep::http::preforked_server::write_socket_to_worker(int, boost::asio::ip::tcp::socket&)':
src/preforked-http-server.cpp:273:40: error: 'native_type' in 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} does not name a type
  typedef boost::asio::ip::tcp::socket::native_type native_type;
                                        ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:38,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/error.hpp:28,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/detail/impl/posix_mutex.ipp:24,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/detail/posix_mutex.hpp:73,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/detail/mutex.hpp:25,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/detail/service_registry.hpp:20,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/impl/execution_context.hpp:20,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/execution_context.hpp:408,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/detail/scheduler.hpp:21,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/system_context.hpp:19,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/impl/system_executor.hpp:22,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/system_executor.hpp:129,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio/associated_executor.hpp:21,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/asio.hpp:21,
                 from ./zeep/http/server.hpp:9,
                 from ./zeep/http/preforked-server.hpp:9,
                 from src/preforked-http-server.cpp:15:
src/preforked-http-server.cpp:281:38: error: 'native_type' was not declared in this scope
    char    control[CMSG_SPACE(sizeof(native_type))];
                                      ^~~~~~~~~~~
src/preforked-http-server.cpp:281:38: note: suggested alternative:
In file included from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/cv_status.hpp:12,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/pthread/condition_variable_fwd.hpp:12,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/pthread/thread_data.hpp:14,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/thread_only.hpp:17,
                 from /opt/gnu/8.3.0/boost/1.69.0/include/boost/thread/thread.hpp:12,
                 from ./zeep/http/server.hpp:10,
                 from ./zeep/http/preforked-server.hpp:9,
                 from src/preforked-http-server.cpp:15:
/opt/gnu/8.3.0/boost/1.69.0/include/boost/core/scoped_enum.hpp:73:10: note:   'boost::native_type'
   struct native_type
          ^~~~~~~~~~~
src/preforked-http-server.cpp:285:31: error: 'union zeep::http::preforked_server::write_socket_to_worker(int, boost::asio::ip::tcp::socket&)::<unnamed>' has no member named 'control'
  msg.msg_control = control_un.control;
                               ^~~~~~~
src/preforked-http-server.cpp:286:41: error: 'union zeep::http::preforked_server::write_socket_to_worker(int, boost::asio::ip::tcp::socket&)::<unnamed>' has no member named 'control'
  msg.msg_controllen = sizeof(control_un.control);
                                         ^~~~~~~
src/preforked-http-server.cpp:295:15: error: 'fdptr' was not declared in this scope
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
               ^~~~~
src/preforked-http-server.cpp:295:15: note: suggested alternative: 'cmptr'
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
               ^~~~~
               cmptr
src/preforked-http-server.cpp:295:40: error: 'native_type' does not name a type; did you mean 'status_type'?
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                        ^~~~~~~~~~~
                                        status_type
src/preforked-http-server.cpp:295:51: error: expected '>' before '*' token
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                   ^
src/preforked-http-server.cpp:295:51: error: expected '(' before '*' token
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                   ^
                                                   (
src/preforked-http-server.cpp:295:52: error: expected primary-expression before '>' token
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                    ^
src/preforked-http-server.cpp:295:71: error: expected ')' before ';' token
  native_type *fdptr = reinterpret_cast<native_type*>(CMSG_DATA(cmptr));
                                                                       ^
                                                                       )
src/preforked-http-server.cpp:296:18: error: 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} has no member named 'native'
  *fdptr = socket.native();
                  ^~~~~~
make: *** [makefile:139: obj/preforked-http-server.o] Error 1
```

It seems zeep does not work with that new a boost?

**Comment by mhekkel** [comment]
That was easy to fix. Yes, libzeep can now compile with boost 1.70 and I tested it with 1.65 as well.
